language: python
sudo: required
services:
  - docker
python:
    - "2.7"
env:
  matrix:
    - TOX_ENV=py27-lint
    - TOX_ENV=py35-lint
    - TOX_ENV=py27-lint-readme
    - TOX_ENV=py27
    - TOX_ENV=py35
  global:
    # do not load /etc/boto.cfg with Python 3 incompatible plugin
    # https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
    - BOTO_CONFIG=/doesnotexist


install:
    - sudo rm /etc/boto.cfg
    # Setup git to allow git operations.
    - git config --global user.name "Travis Test User"
    - git config --global user.email "galaxy_test@galaxyproject.org"
    - pip install tox coveralls
    - docker run -d -e GALAXY_CONFIG_WATCH_TOOL_DATA_DIR=True -p 8080:80 bgruening/galaxy-stable
    - sleep 120
    - docker ps
    - python setup.py install

script:
    - tox -e $TOX_ENV
    - bash test.sh

after_success:
  - coveralls
